### ISSUE TITLE
`converter`: Add option to calculate area and perimeter if missing

### ISSUE THREAD

**Issue by m-mohr** [fiboa/cli#21]

**Comment by m-mohr** [comment]
@cholmes wrote in #38:

> When working with the converter I was thinking that area and perimeter should be pretty easy to calculate from the geometry.
> 
> It seems like you could potentially do them with geopandas, maybe fitting into the template? But it could also be nice to just have them be top-level 'convert' options, to just automatically add them based on the geometry.
> 
> See also - https://github.com/fiboa/specification/issues/28#issuecomment-2095121587 could be nice to have the validator check this as well.

**Comment by m-mohr** [comment]
At first I also thought this is easy and shapely already has the `length` and `area` properties, but they are unitless. Here it depends on the projection though, e.g. the area might also be given in square degrees insteasd of square meters, you need to consider holes, and sometime you even get negative areas. So we may convert to WGS84 for the area, but is that always good? It will be somewhat inaccurate compared to the native CRS (and pyproj is quite a heavy dependency).

See also https://stackoverflow.com/questions/23697374/calculate-polygon-area-in-planar-units-e-g-square-meters-in-shapely

**Comment by cholmes** [comment]
Oh yeah, I remember hitting on some of the inaccuracies of area calculations with different projections when I was working with google buildings. Ended up with [this code](https://github.com/opengeos/open-buildings/blob/276386b24b5a206549504a6c953e09b20f7fe359/open_buildings/google/process.py#L102) - you need to project to something better to calculate the area. 

Just came across: https://gis.stackexchange.com/questions/337035/epsg-codes-for-projections-to-use-when-computing-the-area-of-global-polygon-sets which I appreciate and don't remember at the time. 

I do think it'd be nice to give some option that's opt-in, that may have some caveats. But first key step seems to be to have the validator be good at checking this - since having the area calculated wrong may be a problem with other data.
